clickhouse_imdb:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: imdb
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      user: user
      password: password